#!/usr/bin/env python3
"""people.py - registry, relationship map and safe writers for /people (python3 stdlib only).
Run from the workspace (BRAIN_ROOT for multi-root). Folder names come from brain.config.json.

  --list [--context CTX]              person notes: identity fields, profile flag, last log date, relations (JSON)
  --map CTX [--write]                 mermaid map from the relation lines of auto:profile blocks; --write puts it into
                                      the <!-- auto:map --> block of <primary area of CTX>/<relationship map file>
  --write-block PERSON.md --from F    replace (or add, above `## Log`) the auto:profile block with the file's text
  --log NOTE.md --line "text"         append `- YYYY-MM-DD — text` under `## Log` (section created when missing)

Relation lines inside a profile block: `- [[stem|Name]] — relation — strength 1-5` (strength optional).
`profile: false` in a person's frontmatter = skip that person entirely.
"""
import argparse
import datetime as dt
import json
import os
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "lib"))
import paths  # noqa: E402
import vault  # noqa: E402

TODAY = dt.date.fromisoformat(os.environ["BRAIN_TODAY"]) if os.environ.get("BRAIN_TODAY") else dt.date.today()
PROFILE_RE = re.compile(r"<!-- auto:profile start -->.*?<!-- auto:profile end -->", re.S)
MAP_RE = re.compile(r"<!-- auto:map start -->.*?<!-- auto:map end -->", re.S)
REL_RE = re.compile(r"^- \[\[([^\]|]+)(?:\|[^\]]*)?\]\]\s*[—–-]\s*([^—–\n]+?)(?:\s*[—–-]\s*(\d))?\s*$", re.M)


def fm_of(text):
    fm, _ = vault.frontmatter(text)
    return {k: v.strip("\"'") for k, v in fm.items()}


def people(root, context=""):
    notes = list(paths.iter_people(root))
    titles = {}
    for p in notes:
        titles[vault.nfc(p.stem)] = fm_of(vault.read(p) or "").get("title") or p.stem
    out = []
    for p in notes:
        text = vault.read(p) or ""
        fm = fm_of(text)
        if context and fm.get("context", "") != context:
            continue
        pm = PROFILE_RE.search(text)
        rels = [{"to": titles.get(vault.nfc(a).strip(), a.strip()), "type": b.strip(), "strength": int(c) if c else None}
                for a, b, c in REL_RE.findall(pm.group(0) if pm else "")]
        logs = vault.DATE_RE.findall(vault.section(text, "Log"))
        out.append({"name": titles[vault.nfc(p.stem)], "path": paths.rel(p, root), "context": fm.get("context", ""),
                    "role": fm.get("role", ""), "org": fm.get("org", ""), "email": vault.as_list(fm.get("email")),
                    "aliases": vault.as_list(fm.get("aliases")), "profile": fm.get("profile", "true").lower() != "false",
                    "has_profile": bool(pm), "last_log": max(logs) if logs else "", "relations": rels})
    return out


def node_id(name):
    return "n" + re.sub(r"\W", "", vault.slugify(name).replace("-", "_"))


def render_map(root, context):
    rows = [r for r in people(root, context) if r["profile"]]
    names = {r["name"] for r in rows}
    lines = ["graph LR"]
    for r in rows:
        lines.append(f'  {node_id(r["name"])}["{r["name"]}{(" · " + r["role"]) if r["role"] else ""}"]')
    for r in rows:
        for rel in r["relations"]:
            if rel["to"] not in names:
                lines.append(f'  {node_id(rel["to"])}(["{rel["to"]}"])')
            s = rel["strength"] or 0
            arrow = "==>" if s >= 4 else "-->" if s >= 2 else "-.->"
            lines.append(f'  {node_id(r["name"])} {arrow}|{rel["type"]}| {node_id(rel["to"])}')
    edges = sum(len(r["relations"]) for r in rows)
    return ("<!-- auto:map start -->\n```mermaid\n" + "\n".join(lines) + "\n```\n"
            f"*{len(rows)} people, {edges} relations; generated by /people {TODAY}. "
            "Strength: ==> 4-5, --> 2-3, -.-> 1 or unknown.*\n<!-- auto:map end -->")


def map_path(root, context):
    spec = paths.CFG["contexts"].get(context)
    if not spec:
        sys.exit(f"unknown context {context!r}; known: {', '.join(paths.CONTEXTS)}")
    return root / spec["primary_area"] / paths.RELATION_MAP


def write_map(root, context):
    p = map_path(root, context)
    block = render_map(root, context)
    text = vault.read(p)
    if text is None:
        text = (f"---\ntype: map\ntitle: Relationship map ({context})\ncontext: {context}\ntags: [ctx/{context}]\n---\n\n"
                f"# Relationship map ({context})\n\n{block}\n")
    elif MAP_RE.search(text):
        text = MAP_RE.sub(lambda _: block, text)
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"
    vault.write(p, text)
    return p


def write_block(path, src):
    p = Path(path)
    text = vault.read(p) or ""
    block = "<!-- auto:profile start -->\n" + Path(src).read_text(encoding="utf-8").strip("\n") + "\n<!-- auto:profile end -->"
    if PROFILE_RE.search(text):
        text = PROFILE_RE.sub(lambda _: block, text)
    elif re.search(r"^## Log", text, re.M):
        text = re.sub(r"^## Log", lambda m: block + "\n\n## Log", text, count=1, flags=re.M)
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"
    vault.write(p, text)


def append_log(path, line):
    p = Path(path)
    text = vault.read(p) or ""
    entry = f"- {TODAY.isoformat()} — {line.strip()}"
    m = re.search(r"^## Log[^\n]*\n", text, re.M)
    if m:
        nxt = re.search(r"^(## |<!-- auto:links start)", text[m.end():], re.M)
        end = m.end() + nxt.start() if nxt else len(text)
        text = text[:end].rstrip("\n") + "\n" + entry + "\n" + ("\n" + text[end:] if nxt else "")
    else:
        text = text.rstrip("\n") + "\n\n## Log\n" + entry + "\n"
    vault.write(p, text)


def at(root, p):
    """A note path as given, else relative to the vault root."""
    return Path(p) if Path(p).exists() else root / p


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--context", default="")
    ap.add_argument("--map", metavar="CTX")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--write-block", metavar="PERSON_MD")
    ap.add_argument("--from", dest="src")
    ap.add_argument("--log", metavar="NOTE_MD")
    ap.add_argument("--line")
    ap.add_argument("--json", action="store_true", help="(--list output is always JSON)")
    a = ap.parse_args(argv)
    root = Path(paths.find_root())
    if a.list:
        print(json.dumps(people(root, a.context), ensure_ascii=False, indent=1))
    elif a.map:
        print(paths.rel(write_map(root, a.map), root) if a.write else render_map(root, a.map))
    elif a.write_block:
        if not a.src:
            sys.exit("--from FILE required")
        write_block(at(root, a.write_block), a.src)
    elif a.log:
        if not a.line:
            sys.exit("--line required")
        append_log(at(root, a.log), a.line)
    else:
        ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
